### ISSUE TITLE
Supporting iOS

### ISSUE THREAD

**Issue by Yorik0512** [sicpa-dlab/didcomm-react-native#15]
Hey guys,

I’m new to DIDComm and started investigating options to integrate it for our React Native project where we aim to deliver both Android and iOS apps.
I’ve noticed that this React Native module does not support iOS and you have developed a separate Swift wrapper.

So here are my current questions:
1. What is the state of both mentioned implementations (React Native, Swift), can it be taken for integration to deliver production solution?
2. What was the reason to go this path and have it separate instead of building on top of wasm and adapting it for Android and iOS to be consumed via bridges?
Looking forward to hearing from feedback and continue learning on this matter.

Resources:
Swift wrapper - https://github.com/sicpa-dlab/didcomm-rust/tree/main/wrappers/swift
Wasm - https://github.com/sicpa-dlab/didcomm-rust/tree/main/wasm

Thanks in advance,
Yurii

**Comment by dmitry-vychikov** [comment]
Hello @Yorik0512 
This package is designed as a Wrapper for JVM and Swift implementations to make them usable in React Native. You're right, it doesn't support IOS because it is not implemented yet.

Sorry, adding IOS support for this wrapper is NOT on our roadmap for now.

> What is the state of both mentioned implementations (React Native, Swift), can it be taken for integration to deliver production solution?

React Native over JVM is in early alpha version. You will likely to run into bugs/issues when start using it. We're using DIDComm RN on Android internally, so we're planning to to resolve critical issues.

I'm not sure about Swift implementation though. It should be stable.

> What was the reason to go this path and have it separate instead of building on top of wasm and adapting it for Android and iOS to be consumed via bridges?

Android/IOS do not have in-built WASM runtime. So you would have to run the libraries inside a WebView component, which is challenging too. We believed that developing a RN wrapper over JVM is simpler than adapting WASM for Android/IOS.
